var l,r="undefined"==typeof browser,u=0<navigator.userAgent.indexOf("Edge/"),v=0<navigator.userAgent.indexOf("Firefox/");u&&(browser.app=chrome.app,chrome=browser);
var w=[atob("MTI3LjAuMC4xOjEwMDE="),atob("MC4xLjAuMToxMDAx")],aa=atob("cGx1Z2luLnYzLmludGVybmV0ZG93bmxvYWRtYW5hZ2VyLmNvbQ=="),ba=atob("djYuMjZiMTQ="),ca=atob("djYuMjg="),da=atob("amVhb2hobGFqZWpvZGZqYWRjcG9ucG5qZ2tpaWtvY24="),ea=atob("YWZtZHBtZGRpb2twZGtuYWVvZmRubGNsYnBnZWhoY2U="),fa=atob("Q2hyb21lX1JlbmRlcldpZGdldEhvc3RIV05E"),ga=["main_frame","sub_frame"],x="main_frame sub_frame image object xmlhttprequest other".split(" "),y=["object","xmlhttprequest","other"],ha=[301,302,303,307],z=["http://*/*",
"https://*/*"],ia=/\.([^.\\/]*?)(?:\.[0-9.]+)?$/,ja=/(?:chrome|about|chrome-extension|ms-browser-extension|moz-extension):/,ka=[atob("KjovLyouaW50ZXJuZXRkb3dubG9hZG1hbmFnZXIuY29tL2F1dG9yZWcuaHRtbD8q"),atob("KjovLyouaW50ZXJuZXRkb3dubG9hZG1hbmFnZXIuY29tL2ZpbGxyZWdmb3JtLmh0bWw/Kg==")],la=new RegExp(atob("Xig/Omh0dHB8aHR0cHMpOi8vKD86d3d3XC55b3V0dWJlXC5jb20vd2F0Y2hcP3x3d3dcLmZhY2Vib29rXC5jb20vLisvKD86dmlkZW9zfHBvc3RzKS8oPzp2YlwuXGQrLyk/XGQrXGJ8cGxheWVyXC52aW1lb1wuY29tL3ZpZGVvL1xkKyk="),"i"),ma=new RegExp(atob("Xig/Oltcd1wtXStcLikqPyg/OnlvdXR1YmVcLmNvbXxnb29nbGV2aWRlb1wuY29tKSQ="),
"i"),na=atob("L3ZpZGVvcGxheWJhY2s="),oa=atob("L2FwaS90aW1lZHRleHQ="),pa=atob("L2FwaS9tYW5pZmVzdC9kYXNo"),qa=new RegExp(atob("Xig/Oltcd1wtXStcLikqPyg/OnZpbWVvXC5jb218dmltZW9jZG5cLmNvbSkk"),"i"),ra=atob("cGxheWVyLnZpbWVvLmNvbQ=="),sa=atob("L3ZpZGVvLw=="),ta=new RegExp(atob("Xig/Oltcd1wtXStcLikqP2ZiY2RuXC5uZXQk"),"i"),ua={16:1,17:2,18:4,45:8,46:16},va={http:1,https:129,ftp:2,ftps:130,rtmp:3,rtmpt:3,rtmpe:3,mms:4,idmreg:159},wa={"text/html":"HTML|HTM","text/css":"CSS","text/javascript":"JS|JSON","text/mspg-legacyinfo":"MSI|MSP",
"text/plain":"TXT|SRT","text/srt":"SRT","text/vtt":"VTT|SRT","text/xml":"XML|F4M|TTML","text/x-javascript":"JS|JSON","text/x-json":"JSON","application/f4m+xml":"F4M","application/gzip":"GZ","application/javascript":"JS","application/json":"JSON","application/msword":"DOC|DOCX|DOT|DOTX","application/pdf":"PDF","application/ttaf+xml":"DFXP","application/vnd.apple.mpegurl":"M3U8","application/zip":"ZIP","application/x-7z-compressed":"7Z","application/x-aim":"PLJ","application/x-compress":"Z","application/x-compress-7z":"7Z",
"application/x-compressed":"ARJ","application/x-gtar":"TAR","application/x-gzip":"GZ","application/x-gzip-compressed":"GZ","application/x-javascript":"JS","application/x-mpegurl":"M3U8","application/x-msdos-program":"EXE|DLL","application/x-msi":"MSI","application/x-msp":"MSP","application/x-ole-storage":"MSI|MSP","application/x-rar":"RAR","application/x-rar-compressed":"RAR","application/x-sdlc":"EXE|SDLC","application/x-shockwave-flash":"SWF","application/x-silverlight-app":"XAP","application/x-subrip":"SRT",
"application/x-tar":"TAR","application/x-zip":"ZIP","application/x-zip-compressed":"ZIP","video/3gpp":"3GP|3GPP","video/3gpp2":"3GP|3GPP","video/avi":"AVI","video/flv":"FLV","video/mp2t":"TS|M3U8","video/mp4":"MP4|M4V","video/mpeg":"MPG|MPEG","video/mpg4":"MP4|M4V","video/msvideo":"AVI","video/quicktime":"MOV|QT","video/webm":"WEBM","video/x-flash-video":"FLV","video/x-flv":"FLV","video/x-mp4":"MP4|M4V","video/x-mpg4":"MP4|M4V","video/x-ms-asf":"ASF","video/x-ms-wmv":"WMV","video/x-msvideo":"AVI",
"audio/3gpp":"3GP|3GPP","audio/3gpp2":"3GP|3GPP","audio/mp3":"MP3","audio/mp4":"M4A|MP4","audio/mp4a-latm":"M4A|MP4","audio/mpeg":"MP3","audio/mpeg4-generic":"M4A|MP4","audio/mpegurl":"M3U|M3U8","audio/webm":"WEBM","audio/wav":"WAV","audio/x-mpeg":"MP3","audio/x-ms-wma":"WMA","audio/x-wav":"WAV","ilm/tm":"MP3","image/gif":"GIF|GFA","image/icon":"ICO|CUR","image/jpg":"JPG|JPEG","image/jpeg":"JPG|JPEG","image/png":"PNG|APNG","image/tiff":"TIF|TIFF","image/vnd.microsoft.icon":"ICO|CUR","image/webp":"WEBP",
"image/x-icon":"ICO|CUR","flv-application/octet-stream":"FLV"};function A(){this.b=this.constructor.prototype.f++}A.prototype.f=1;function xa(a,b,c,d){this.id=a;this.port=b;this.b=c;this.url=d}xa.prototype.a=0;function ya(a,b,c){this.id=[a,b].toString();this.b=0>c?null:[a,c].toString()}
function C(a,b,c,d,e,f){if(a){var h=["MSG#",a,"#",b,"#",c,"#",d];this.g=a;this.f=b;this.h=c;this.i=d;this.a=e||[];this.j=h;if(e)for(a=0;a<e.length;a++)h.push(":",e[a]||0);if(f)for(var g in f)if(e=f[g],null!=e)if(h.push(",",g,"="),"number"==typeof e)h.push(e);else{b=a=e.length;for(c=0;c<b;)d=e.charCodeAt(c++),128<=d&&(2048<=d?(a+=2,d-55296&56320||c++):a++);h.push(a,":",e)}}else this.c=new FileReader}function za(a){a.N||(a.j.push(";"),a.N=!0);return new Blob(a.j)}
function Aa(a,b,c){a.N?a.v(a):(b.a=c||0,b.b=0,a.c.onload=a.Ha.bind(a,b),E(a,b,0,50))}l=C.prototype;
l.Ha=function(a){for(var b=this.c.result;;)switch(a.b){case 0:var c=b.split(",",2),d=c.shift().split(":",2),e=d.shift();if(!d.length){if(!c.length)return this.v(this);a.b=1}var f=e.length+1,d=e.split("#",6);if(5!=d.length||"MSG"!=d[0])return this.v(this);this.g=parseInt(d[1]);this.f=parseInt(d[2]);this.h=parseInt(d[3]);this.i=parseInt(d[4]);b=b.slice(f);a.a+=f;a.b++;break;case 1:d=b.split(",",2);e=d.shift();if(!d.length){d=b.split(";",2);if(2>d.length)return E(this,a,b.length,100);a.b=4}f=e.length+
1;this.a=d=e.split(":");for(e=0;e<d.length;e++)c=d[e],d[e]=c.includes(".")?parseFloat(c):parseInt(c);b=b.slice(f);a.a+=f;a.b++;break;case 2:c=b.split(",",2);2>c.length&&(c=b.split(";",2));var d=c.shift().split(":",2),h=d.shift(),f=h.length,e=!1;if(d.length)f++;else{if(!c.length)return E(this,a,b.length,25);e=!0}d=h.split("=",3);if(2!=d.length)return this.v(this);c=parseInt(d[0]);d=parseInt(d[1]);a.a+=f;a.b++;if(e){this[c]=d;b=b.slice(f);a.b++;break}a.f=c;a.c=d;b=a.c;f=a.a;a=a.slice(f,f+b);a.size==
b?this.c.readAsText(a):this.v(this);return;case 3:return this[a.f]=b,a.a+=a.c,a.b++,E(this,a,0,21);case 4:switch(b[0]){case ",":a.b=2;b=b.slice(1);break;case ";":a.b++;break;default:return this.v(this)}a.a++;break;case 5:this.N=!0;this.K(this);a.size>a.a&&(b=new C,b.K=this.K,b.v=this.v,Aa(b,a,a.a));return}};function E(a,b,c,d){var e=b.a;c=e+c;b.size>c?a.c.readAsBinaryString(b.slice(e,c+d)):a.v(a)}l.l=null;l.K=null;l.v=null;l.N=!1;
function F(){var a=this.constructor.prototype,b;for(b in a)b.startsWith("_")||"constructor"==b||(this[b]=a[b].bind(this));b=navigator.userAgent;a=b.match(/\b(?!(?:Safari|Chrome|Gecko)\/)\w+\/(\d+)(?:.(\d+))?(?:.(\d+))?(?:.(\d+))?\b(?!.*[()])/);if(b=v?a:b.match(/\bChrome\/(\d+)\.(\d+)\.(\d+)\.(\d+)\b/)){this.R=b[1]<<24|b[2]<<22|b[3]<<8|b[4];this.oa=b[0];this.ja=a?a[0]:b[0];this.ma=[];this.ha=!1;this.c={};this.u={};this.a={};this.j={};this.b={};this.i={};this.f={};this.g={};this.w={};this.T="";this.U=
!0;this.Da=this.na=this.Ca=1;this.h=this.ia=null;this.P=1;this.m=!1;this.H=this.O=0;this.la=null;this.S=this.B=!1;chrome.windows.onCreated.addListener(this.va);chrome.windows.onRemoved.addListener(this.wa);chrome.windows.onFocusChanged.addListener(this.Ua);chrome.tabs.onActivated.addListener(this.Oa);chrome.tabs.onUpdated.addListener(this.Qa);chrome.tabs.onAttached&&chrome.tabs.onAttached.addListener(this.Pa);a=chrome.runtime.getBrowserInfo;b=chrome.webRequest.ResourceType;a&&a(this.Va);b&&b.MEDIA&&
x.push("media")&&y.push("media");try{chrome.windows.getAll({windowTypes:["normal","popup"]},this.sa)}catch(c){chrome.windows.getAll(this.sa)}this.W();Ba(this,!0)}}l=F.prototype;l.Va=function(a){var b=a.version.split(/\D+/);this.R=b[0]<<24|b[1]<<22|b[2]<<8|b[3];this.oa=this.ja=a.name+"/"+a.version};
function Ba(a,b){var c=a.c;a.ia=null;chrome.contextMenus.removeAll();for(var d=0;d<Ca.length;d++){var e=Ca[d];if(b||!v||c[e[0]]){var f=chrome.contextMenus.create({title:chrome.i18n.getMessage(e[1]),contexts:e[2].split(","),onclick:e[3].bind(a),enabled:!0});"menu_download_selected"==e[1]&&(a.ia=f)}}}function Da(a,b,c,d,e){a=a.f;return b in a?a[b]:a[b]=new xa(b,c,d,e)}
function G(a,b){var c=a.g,d=b.requestId;c[d]=b;var e=b.id;e||(e=b.id=u?a.Da++:d);e!=d&&(c[e]=b,c=a.j[[b.tabId,b.frameId]])&&(c.a=e)}function H(a,b){var c=a.i[b];c&&delete a.i[b];return c}l.W=function(){var a=new WebSocket("ws://"+w[this.O%w.length]+"/?cid="+Math.random().toString().substr(2,9),aa);this.pa=a;a.onopen=this.ua;a.onclose=this.Z;a.onmessage=this.Na;1==a.readyState?this.ua():3==a.readyState&&this.Z()};
l.ua=function(){this.m=!0;this.na=1;var a=chrome.i18n.getUILanguage().replace("_","-");"sr"==a&&(a+="-Cyrl-CS");var b={};b[112]=this.ja;b[113]=this.oa;b[114]=fa;b[116]=a;I(this,2,0,[3,1,7,0],b)};l.Z=function(){this.pa=null;if(this.m){this.m=!1;this.w={};for(var a=this.ma,b=0;b<a.length;b++){var c=a[b],d=c.splice(0,2).pop();a.splice(b--,1);u&&c.splice(1);d.removeListener.apply(d,c)}this.ha=!1}a=++this.O;b=w.length;c=a/b;120>c&&(1==c&&this.U&&this.V(),!a||a%b?this.W():window.setTimeout(this.W,5E3*c))};
l.Na=function(a){var b=new C;b.K=this.Ja;b.v=this.Z;Aa(b,a.data)};function I(a,b,c,d,e){if(!a.m)return!1;var f=a.na++;b=new C(f,b,1,c,d,e);a.pa.send(za(b));c&1&&(a.w[f]=b);return!0}
function Ea(a,b){var c=a.g;if(b.a){var d=b.a[6],e=d&&c[d];if(e){var f=e.type;return!f||"image"==f||e.c?(b.l=e.port.id,b.m=d,!0):!1}}var h=a.a,g=a.f,k=b[6],m=b[17],n=b[50],p=b[7],t,B;for(d in c){var e=c[d],q=e.url;if(q){if(q==k||q==m)if(f=e.type,!f||"image"==f||e.c)return b.l=e.port.id,b.m=parseInt(d),!0;q==n&&(B=e.port.id)}}for(d in g)if(c=g[d],q=c.url){if(q==k||q==m||q==n)if(e=c.port,p&&(f=h[e.tabId])&&f.url!=p&&(e=null),e)return b.l=e.id,!0;q==p&&(t=c.port.id)}return null!=B?(b.l=B,!0):null!=t?
(b.l=t,!0):!1}l.ra=function(a,b,c,d){if(b)return d?(b=(c=d.shift())&&this.a[c.id])?a.l=b.id:null:null;if(null!=a.l)return a.l;if(a.a){var e=a.a[7];if(e&&this.u[e])return a.l=e}if(Ea(this,a))return a.l;d=this.u;var f=a[50],h=a[7];for(e in d){b=d[e];if(b.url==f){a.l=e;break}null==a.l&&b.url==h&&(a.l=e)}if(null!=a.l)return a.l;h&&chrome.tabs.query({url:h},J(this,a,!0,c));return null};
l.X=function(a,b,c,d,e){var f=a.tabId,h=a.frameId,g=a.windowId,k;if(void 0===b&&(b=new K(this,a,!0),null==g&&(a.a?(chrome.tabs.get(f,L(b,2)),chrome.windows.getLastFocused(L(b,3))):(g=this.a[f],a.windowId=g&&g.windowId)),null==h&&a.url&&chrome.webNavigation.getAllFrames({tabId:f},L(b,4)),b.c()))return;c&&0<=c.index?a.windowId=c.windowId:d&&(a.windowId=d.id);if(e)for(d=e.length-1;0<=d;d--)if(c=e[d],!c.Wa&&c.frameId&&c.url==a.url){h=a.frameId=c.frameId;k=c.parentFrameId;break}null==h?a.url||a.postMessage([11,
f,null,!0,a.b]):(e=[f,h].toString(),c=this.j[e],this.a[e]=a,0<=k&&(a.c=[f,k].toString()),c&&(a.i=c.a,a.b=c.c,(k=c.D)&&a.url!=k&&(a.D=k),!a.c&&c.b&&(a.c=c.b)),a.postMessage([11,f,h,!a.url,a.b]))};l.ca=function(a,b,c,d){var e=M(a,!0);if(!e)return 0;if(1==e&&void 0===d)return chrome.cookies.getAll({url:a},J(this,a,b,c)),-1;"object"==typeof d&&(d=N(d));var e=[e],f={};f[6]=a;f[8]=c;f[51]=d;f[54]=navigator.userAgent;f[7]=b;I(this,14,0,e,f);return 3};
l.za=function(a,b,c,d,e){if(!d){if(!a||!a.length)return;c||(c={});var f=new K(this,a,b,c,!0);c.Ba&&!c.xa&&chrome.cookies.getAll({url:c.Ba},L(f,4));for(var h=0;h<a.length;h++)chrome.cookies.getAll({url:a[h][0]},L(f,h+5));if(f.c())return}e&&(c.xa=N(e));for(h=0;h<a.length;h++)a[h][4]=N(arguments[h+5]);var f=0,h=[a.length],g={8:4};g[54]=navigator.userAgent;g[7]=c.Ba;g[110]=c.F;g[111]=c.xa;1<a.length&&(I(this,15,f,h,g),f=16,g={});for(var h=[0],k;k=a.shift();)g[6]=k[0],g[102]=k[2],g[50]=k[3],g[51]=k[4],
I(this,14,f,h,g)};function O(a,b,c,d){(b=b[c])?(b=d?b.replace(/\./g,"\\.").replace(/\?/g,".").replace(/\*/g,".*").replace(/~/g,"(?:.*\\.)?"):b.replace(/\?/g,".").replace(/\*/g,".*"),b="^(?:"+b.replace(/\|{2,}/g,"|")+")$"):b="(?!)";a.c[c]=new RegExp(b,"i")}
function P(a,b,c,d,e,f,h,g){if(!d||a.c[-8]){var k=a.a[b];if(k){var m;m=new A;m=a.i[m.b]=m;var n=m.b;m.tabId=b;m.port=k;m.j=c;m.c=0;m.m=[];if(k=d&&!!e)m.B=!0,m.u=e,m.h=f,m.i=h,m.zoom=g,e.a||Q(a,e);e="^(?:http|https|ftp|ftps|rtmp|rtmpt|rtmpe|mms)://";d&&(d=a.c[12])&&(d=d.replace(/\./g,"\\."),d=d.replace(/\*/g,".*"),d=d.replace(/\~/g,"(?:.*\\.)?"),e=e+"(?:[^\\/]*@)?(?:"+d+")(?::\\d+)?(?:\\W|$)");m.g=R(a,b,[12,n,c,k,e]);m.w=0;m.g||H(a,n)}}}
l.G=function(a,b,c){if(4294967295==a)this.h=null,c=!0;else{var d=this.f[a];if(d){c=d.a;if(!c)return;if(b)switch(c){case 3:return;case 2:break;default:d.a=3;window.setTimeout(this.G.bind(null,a,!1,!0),1E3);return}d.a=0;c=!0}}c&&I(this,8,32,[a])};function Fa(a,b){var c=a.b[b];if(c&&c.L){var d=c.border,e=c.scale;I(a,7,0,[b,d,c.fa,Math.round(c.width*e)-d,Math.round(c.height*e)-d])}}
function S(a,b,c,d){var e=a.f[b],f=256;2==e.a&&(d?(f|=128,e.a=1):f|=64);var h,g,k,m,n;c&&(h=c.left,g=c.top,k=c.right||h+1,m=c.bottom||g+1,n=c.zoom,c=e.port.f)&&(h+=c.left,g+=c.top,k=Math.min(k+c.left,c.right),m=Math.min(m+c.top,c.bottom));I(a,9,f,[b,h,g,k,m,n])}
l.J=function(a){var b=this.b,c=[];if(a)(a=b[a])&&(a.A||a.C||c.push(a.s));else for(var d in b)a=b[d],a.A||a.C||c.push(a.s);if(c.length){b=[15,null,null];a={};var e=this.f;for(d in e){var f=e[d];f.a&&0<=c.indexOf(f.port.tabId)&&(f.b?(f=f.port,f.a||Q(this,f,null,a),b[2]=d,f.postMessage(b)):S(this,d,null,!0))}}};function T(a,b,c){if((b=a.b[b])&&!b.C){b=b.s;var d=c?0:2;c=c?32:64;var e=a.f,f;for(f in e){var h=e[f];h.a&&h.port.tabId==b&&h.a!=d&&(h.a=d,I(a,8,c,[f]))}}}
function U(a,b,c,d){var e=a.H,f=(e&b)!=((c?63:32)&b);a.H=c?e|=b:e&=~b;f&&(c=a.c[-1],b=a.c[-2],c=a.B=0!=c&&(e&c)==c,e=a.S=0!=b&&(e&b)==b,a.la=(c||e)&&d||null)}l.ga=function(a,b,c,d){var e=this.b[a];if(e)if(d)e.C&&window.clearTimeout(e.C),e.C=window.setTimeout(this.ga.bind(null,a,b,c),d);else if(e.C=null,b&&(chrome.windows.get(a,this.I),chrome.tabs.query({windowId:a,active:!0},this.I)),c){if((a=this.b[a])&&!a.C){a=a.s;b=this.f;for(var f in b)c=b[f],c.a&&c.port.tabId==a&&1==c.a&&I(this,8,1152,[f])}}else this.J(a)};
l.I=function(a){a instanceof Array&&(a=a.shift());if(a){var b=a.windowId||a.id,c=this.b[b];if(c){var d=!!a.windowId;if(!(d&&c.ready&&ja.test(a.url))){if(d)c.s=a.id,a.width&&(c.ea=a.width),a.height&&(c.da=a.height);else{var e="fullscreen"==a.state,f=e!=c.A;c.A=e;c.Ga="maximized"==a.state;u?(d=c.scale,c.width=Math.round(a.width/d),c.height=Math.round(a.height/d),c.left=Math.round(a.left/d),c.top=Math.round(a.top/d)):(c.width=a.width,c.height=a.height,c.left=a.left,c.top=a.top);f&&(e?T(this,b):this.J(b))}f=
c.ea;a=c.da;if(f&&a){var h=c.width,e=c.height;if(!c.ready){if(f>h||a>e)return chrome.windows.get(b,this.I);c.ready=!0}d=c.scale;f=(h-f)/2;25>=f&&(c.border=Math.round(f*d));a=e-a-f;150>=a&&(c.fa=Math.round(a*d))}Fa(this,b)}}}};function Q(a,b,c,d){a=a.a;c=[16,c];for(var e=[b],f;f=a[b.c];b=f){if(d)if(d[b.id])break;else d[b.id]=!0;e.push(f)}for(f=e.pop();b=e.pop();f=b)d=b.Fa,c[2]=d,c[3]=b.frameId,c[4]=d?null:b.url,c[5]=d?null:b.D,f.postMessage(c)}
function R(a,b,c){a=a.a;b=[b,null].toString();var d=0,e;for(e in a)e.startsWith(b)&&(a[e].postMessage(c),d++);return d}l.M=function(a){function b(a){a;chrome.runtime.lastError}var c={file:"content.js",runAt:"document_start",allFrames:!0};620756992<=this.R&&(c.matchAboutBlank=!0);if(a instanceof Array)for(;a.length;)try{chrome.tabs.executeScript(a.shift().id,c,b)}catch(d){}else try{chrome.tabs.executeScript(a.id||a,c,b)}catch(d){}};
function Ga(a,b){"object"!=typeof b&&(b=a.b[b]);b&&null==b.L&&I(a,6,17,[b.id,0,b.width,b.height,b.left,b.top,b.scale])}l.sa=function(a){for(;a.length;)this.va(a.shift(),!0)};l.Ea=function(a,b){if(!this.m)return V(b.id,"cannot_contact_idm");var c=a.linkUrl||a.srcUrl;c&&this.ca(c,a.pageUrl,4)};l.qa=function(a,b){if(!this.m)return V(b.id,"cannot_contact_idm");P(this,b.id,a.menuItemId==this.ia)};
l.Ka=function(a){var b=a.sender.tab;if(b&&!(0>b.id)){var c=a.id;null==c&&(c=a.id=a.portId_||this.Ca++);var d=b.id,e="top"==a.name;a.tabId=d;a.windowId=0>b.index?null:b.windowId;a.g=!0;a.h=!1;a.a=e;a.frameId=e?0:a.sender.frameId;a.j=0;a.url=a.sender.url||e&&b.url||null;a.D=null;this.u[c]=a;e&&(this.a[d]=a);a.onMessage.addListener(this.La.bind(this,a));a.onDisconnect.addListener(this.Y);this.X(a)}};
l.Y=function(a,b){if(a.g){b||(a.g=!1);var c=this.f,d=this.g,e=this.i,f,h,g;for(g in c)if(f=c[g],f.port===a)f.a&&this.G(g),delete c[g];for(g in d)(h=d[g],h.port!==a||h.u)||(delete d[g],u&&delete d[h.id]);for(g in e)e[g].port===a&&delete e[g];this.la===a&&U(this,63,!1);if(!b){c=a.tabId;d=a.frameId;e=[c,d].toString();f=this.j;for(g in f)e==f[g].b&&delete f[g];a.a&&delete this.a[c];delete this.a[[c,d]];delete this.u[a.id]}}};
l.La=function(a,b){switch(b[0]){case 21:var c=b[1];c&&(a.url=c,null==a.frameId&&this.X(a));break;case 22:var d=this.a,e=d[[a.tabId,b[2]]],c=b[4];e.Fa=b[3];e.f=c;if(d=d[e.c])if(d=d.f)c.left+=d.left,c.top+=d.top,c.right=Math.min(c.right+d.left,d.right),c.bottom=Math.min(c.bottom+d.top,d.bottom);break;case 23:var c=a.windowId,f=a.tabId,h=b[1],d=b[2],e=b[4],g=this.b[c];if(h){if(h=H(this,h)){var g=f==g.s&&!g.A,k=!d||!e;k&&(d=f);if(f=b[7])h.a&&h.F&&h.a!=h.F||(h.a=f),h.F=f;var m=Da(this,d,a,k?null:b[5],
k?null:b[6]),n=g&&!m.a;m.a=g?1:2;h instanceof C&&W(this,h,2,(g?128:64)|(k?512:0),c,d,f);k||(S(this,d,e),n&&window.setTimeout(this.J.bind(null,c),3E3))}}else b[3]?(this.G(d,!0),delete this.f[d]):e&&f==g.s&&!g.A&&S(this,d,e,!0);break;case 24:c=b[2];(d=this.i[b[1]])&&c&&(d.a&&d.F&&d.a!=d.F||(d.a=c),d.F=c);break;case 25:Da(this,b[1],a,b[2],b[3]);break;case 26:P(this,a.tabId,!0,!0,a,b[1],b[2],b[3]);break;case 27:if(c=this.i[b[1]]){d=c.m;if(e=b[4])if("string"==typeof e&&(e=JSON.parse(e)),e instanceof Array){if(h=
b[5])for(g=0;g<e.length;g++)e[g][3]=h;Array.prototype.push.apply(d,e)}b[3]&&(c.c+=b[3]);b[6]&&(c.pageUrl=b[6]);b[7]&&(c.F=b[7]);++c.w<c.g||(H(this,c.b),c.B?(d=this.b[c.port.windowId])&&d.s==c.tabId&&c.c&&(c.frame=c.u.f,e=c.zoom,I(this,10,0,[4294967295,d.id,Math.round(c.h*e)+d.border,Math.round(c.i*e)+d.fa,0,c.c]),this.h=c.tabId,R(this,c.tabId,[13,!0])):d.length?this.za(d,c.j,c.H):V(c.tabId,"cannot_find_links"))}break;case 28:this.G(4294967295);break;case 29:Ha(this,a.windowId,a.tabId);break;case 30:Ha(this,
a.windowId,a.tabId,b[1],b[2]);break;case 31:(c=ua[b[1]])&&U(this,c,b[2],a);break;case 32:0==b[1]&&U(this,32,b[2],a);break;case 33:U(this,63,!1);break;case 34:if(c=b[2],d=b[3],e=a.m||a.i)e=[e,c],h={},g=32,h[110]=b[1],h[115]=d,-2==c&&(g|=16),I(this,16,g,e,h)}};
l.Ja=function(a){var b=a.f,c=a.h,d=a.i,e=a.a,f;if(1==b){var h=e[0];if(f=this.w[h])b=f.f,delete this.w[h]}switch(b){case 3:this.O=-1;this.T=a[13]||"m"+e[2];if(d=e[4]){d/=96;a=this.R;this.P=620756992>a?1:620756992<=a&&621284967>a?d:637534208<=a&&638078312>a?d:1.25<d?d:1;d=this.b;a=this.P;for(var g in d)e=d[g],e=[g,e.L,e.width,e.height,e.left,e.top,e.scale=a],I(this,6,17,e)}this.U&&this.V();break;case 4:g=this.c;g[-9]=0<(d&64);g[-8]=0<(d&32);g[-4]=0<(d&2);g[-11]=0<(d&256)||2>c;g[-12]=0<(d&512)||2>c;
g[-1]=e[0];g[-2]=e[1];g[12]=a[12];O(this,a,1);O(this,a,2);O(this,a,3);O(this,a,4);O(this,a,10);O(this,a,9,!0);O(this,a,11,!0);if(g=a[13])this.T=g;Ba(this);this.ha||(this.ha=!0,this.o(1,chrome.runtime.onConnect,this.Ka),this.o(1,chrome.webNavigation.onCommitted,this.ta),this.o(1,chrome.webNavigation.onHistoryStateUpdated,this.Ia),this.ka?(this.o(2,chrome.webRequest.onBeforeRequest,this.$,{urls:["*://*/*"],types:x},["requestBody","blocking"]),this.o(2,chrome.webRequest.onBeforeSendHeaders,this.aa,{urls:["*://*/*"],
types:x},["requestHeaders","blocking"]),this.o(2,chrome.webRequest.onHeadersReceived,this.ba,{urls:["*://*/*"],types:x},["responseHeaders","blocking"])):(this.o(2,chrome.webRequest.onBeforeRequest,this.$,{urls:["http://*/*"],types:ga}),this.o(2,chrome.webRequest.onBeforeRequest,this.$,{urls:["https://*/*"],types:x},["requestBody","blocking"]),this.o(2,chrome.webRequest.onBeforeSendHeaders,this.aa,{urls:["http://*/*"],types:x},["requestHeaders"]),this.o(2,chrome.webRequest.onBeforeSendHeaders,this.aa,
{urls:["https://*/*"],types:x},["requestHeaders","blocking"]),this.o(2,chrome.webRequest.onHeadersReceived,this.ba,{urls:["http://*/*"],types:x},["responseHeaders"]),this.o(2,chrome.webRequest.onHeadersReceived,this.ba,{urls:["https://*/*"],types:x},["responseHeaders","blocking"])),this.o(3,chrome.webRequest.onResponseStarted,this.Ta,{urls:["<all_urls>"],types:x}),this.o(3,chrome.webRequest.onErrorOccurred,this.Sa,{urls:["<all_urls>"],types:x}),this.o(3,chrome.webRequest.onBeforeRequest,this.Ra,{urls:ka,
types:ga},["blocking"]),chrome.tabs.query({url:z[0]},this.M),chrome.tabs.query({url:z[1]},this.M));break;case 5:g=e[0];(a=this.b[g])?(d=0!=(d&128),a.A!=d&&(a.A=d)&&T(this,g)):this.wa(g);break;case 6:if(d&4)break;g=f.a[0];d=e[1];if(a=this.b[g])a.L=d,Fa(this,g);break;case 8:g=e[0];d&=32;if(4294967295==g)R(this,this.h,[13,!1]),this.h=null;else if(g=this.f[g])g.a=d?0:2;break;case 11:g=e[0];4294967295==g&&(P(this,this.h,!0,!0),this.h=null);break;case 12:try{var k=a.a[5],m=a[4];g=4==k?2:3;if((1==k||2==
k)&&Ea(this,a)){if(this.c[3].test(m))1==k?g=4:k=4;else if(this.c[-4]||this.c[4].test(m))g=4;a[8]|=256}if(4==k){switch(a.a[4]){case 1:a[7]||(a[7]=a[50]);break;case 3:a[7]||(a[7]=a[32]),a[50]||(a[50]=a[31])}this.ya(a)}else W(this,a,g)}catch(n){W(this,a,0)}break;case 13:X(this,f.a[0],null,3==e[1]);break;case 1:break;default:!f&&d&1&&I(this,1,0,[a.g,0,0,0])}};
l.ya=function(a,b,c){try{if(null==a.l)if(!b){var d=new K(this,a,!0);this.ra(a,null,d)||chrome.windows.getLastFocused(L(d,2));if(d.c())return}else if(c){var e=this.b[c.id],f=this.a[e&&e.s];f&&(a.l=f.id)}f=this.u[a.l];if(!f)return W(this,a,0);var h;var g=a.b;g||(g=A.prototype.f++,a.b=g,this.i[g]=a);h=g;if(!f.a){var k=this.a[f.tabId];k&&k.postMessage([14,h])}var m=[15,h,null,a[6],a[17],a[50],a[31]];f.a||Q(this,f,h);f.postMessage(m)}catch(n){W(this,a,0)}};
function W(a,b,c,d,e,f,h){-1!=c&&(e=[b.g,c,e,f],f={},f[8]=b[8],h&&(f[110]=h),I(a,1,d|(0==c?4:2),e,f))}l.ta=function(a,b){var c=this.a[[a.tabId,a.frameId]];if(c)if(b){var d=a.url;d!=c.url&&(c.url=d,c.j++,la.test(d)&&(c.b=!0),this.Y(c,!0),c.postMessage([17,!1,c.b]))}else this.Y(c)};l.Ia=function(a){return this.ta(a,!0)};
l.va=function(a,b){var c=a.id,d={id:c,width:a.width,height:a.height,left:a.left,top:a.top,scale:this.P,border:8,fa:73,Ga:"maximized"==a.state,A:"fullscreen"==a.state,da:0,ea:0,s:0,ready:!v,L:null,C:null};this.b[c]=d;chrome.tabs.query({windowId:c,active:!0},this.I);chrome.tabs.query({windowId:c,url:z[0]},this.M);chrome.tabs.query({windowId:c,url:z[1]},this.M);b&&Ga(this,d)};l.wa=function(a){I(this,5,32,[a]);delete this.b[a]};
l.Ua=function(a){if(0<a){var b=this.b[a];b&&(Ga(this,b),u&&this.ga(a,!1,!0,500))}};l.Qa=function(a,b,c){var d=c.windowId,e=this.b[d];e&&!e.s&&this.I(c);"complete"==b.status&&(a=this.a[a])&&!a.h&&(a.h=!0,this.J(d))};l.Oa=function(a){this.H=0;this.h&&this.G(4294967295);var b=a.windowId;a=a.tabId;var c=this.a[a];c&&!c.windowId&&(c.windowId=b);if(c=this.b[b])T(this,b),c.s=a,chrome.tabs.get(a,this.I),this.J(b)};
l.Pa=function(a,b){var c=b.Xa,d=this.u,e;for(e in d)(port=d[e])&&port.tabId==a&&(port.windowId=c);T(this,c,!0)};function Ha(a,b,c,d,e){a.h&&a.G(4294967295);var f=a.b[b];f&&f.s==c&&(d&&(f.ea=d),e&&(f.da=e),T(a,b),a.ga(b,d||e,!1,250))}
function Y(a,b){a.sendRequest(b,5);var c=b.requestHeaders,d=new XMLHttpRequest;d.timeout=1E4;d.onreadystatechange=a.Ma.bind(null,d,b.id);d.open("GET",b.url,!0);for(var e=0;e<c.length;e++){var f=c[e];f.name.toLowerCase().startsWith("x-")&&d.setRequestHeader(f.name,f.value)}d.send();return 2}l.Ma=function(a,b){if(4==a.readyState){var c=[b,0],d={};200==a.status&&(d[115]=a.responseText);I(this,16,48,c,d)}};
function Ia(a,b){if(b.f)return b.j=3,b.b|=2052,5;var c=a.c,d=new URL(b.url),e=Ja(d.pathname);if(e&&!d.search&&b.h&&c[2].test(e))return 1;if(!v||b.c||d.search||c[9].test(d.hostname)||!c[1].test(e))return 4;b.j=1;b.b|=8;return 5}
function Ka(a,b){if(b.H)return a.sendRequest(b,6),1;var c=b.f,d=b.statusCode;if(!c&&200!=d&&206!=d)return 1;var e=a.c,f=b.url,d=b.c,h=Z(b.responseHeaders,"Content-Type"),g=Z(b.responseHeaders,"Content-Disposition"),k=La(h).toLowerCase(),m="attachment"==La(g).toLowerCase();if(!c){var n=b.h&&!m&&"text/html"==k;if(b.u)if(n){var p=a.j[[b.tabId,b.frameId]];p&&(p.c=!0);a.sendRequest(b,5)}else"application/json"==k&&(p=a.a[[b.tabId,b.frameId]])&&p.b&&(p.m=b.id,a.sendRequest(b,5));if(n)return 1}if(b.i||!d&&
!e[-9])return 1;var n=c,p=!1,f=new URL(f),t=f.hostname,B=f.pathname,q=Ma(g,"filename")||Ma(h,"name"),g=q&&Ja(q),D=!1,h=!1;if(q)if(g||c)D=h=!0,b.fileName=q,b.w=g;else if(!d)return 1;h||(q=B.split("/").pop(),g=Ja(q));if(!c){q=ma.test(t);if(d&&q){if(B.startsWith(oa)&&"text/xml"==k&&a.sendRequest(b,5),B.startsWith(pa)&&"video/vnd.mpeg.dash.mpd"==k)return Y(a,b)}else if(d&&qa.test(t)){if("M4S"==g)return 1;if(t==ra&&B.startsWith(sa)&&"application/json"==k)return Y(a,b)}else if(m&&ta.test(t)&&"image"==b.type&&
"MP4"==g)return 1;if(!D){if(t=wa[k])if(t=t.split("|"),g&&0<=t.indexOf(g))D=!0;else if(d||!g)g=t.shift(),D=!0;if(!g)if(d&&q&&B==na)p=!0;else return 1;!g||D||!m&&k&&!e[10].test(k)||(D=!0);D&&(b.w=g)}if(d&&D&&"M3U8"==g)return Y(a,b);if(d&&"ASF"==g&&((k=Z(b.responseHeaders,"Content-Length"))&&102400>=parseInt(k)||"DCLK-AdSvr"==Z(b.responseHeaders,"Server")))return 1;d&&e[3].test(g)?p=!0:e[1].test(g)&&(n=d?!e[-4]&&!e[4].test(g):!0)}if(!n&&!p||(e=p?e[11]:c?null:e[9])&&e.test(f.hostname))return 1;b.j=n?
2:4;b.b|=c?2052:p?256:(d?4096:0)|(h||m?16:8);return n?3:2}
l.sendRequest=function(a,b,c){var d=a.a,e=a.requestHeaders;if(1==(d&31)&&null==e&&void 0===c)return chrome.cookies.getAll({url:a.url},J(this,a,b)),!0;"object"==typeof c&&(c=N(c));var f=a.id,h=a.port&&a.port.id,g=a.timeStamp,k=a.responseHeaders,m=a.B,n=a.b;null==b&&(b=a.j);d&64&&(n|=2097152);"POST"==a.method&&(n|=512);var p=0,d=[f,h,Math.floor(g/1E3),Math.floor(g%1E3*1E3),d&31,b],f={};v&&4>b&&(p|=1);a.c&&(p|=16);f[6]=Na(a.url);f[17]=a.D;f[4]=a.w;f[100]=a.fileName;f[8]=n;f[11]=Oa(e);f[13]=Oa(k);f[18]=
Oa(m);a.g&&(f[14]=Pa(a.g,Z(e,"Content-Type")));a.m&&(f[19]=Pa(a.m,Z(m,"Content-Type")));null==e&&(f[50]=a.port&&a.port.url,f[51]=c,f[54]=navigator.userAgent);if(a=this.a[a.tabId])f[7]=a.url,f[110]=a.title;return I(this,13,p,d,f)};
function X(a,b,c,d){var e=a.g,f,h;"object"==typeof b?f=b.requestId:(f=b,b=e[f]);d&&(c||r?h={redirectUrl:chrome.extension.getURL("captured.html")}:h={cancel:!0});if(b){delete e[f];u&&delete e[b.id];(f=b.resolve)&&void 0!==d&&(b.resolve=b.reject=null,f(h||{}));if(d=b.reject)b.resolve=b.reject=null,d();b.c&&(e[b.id]={url:b.url,port:b.port});!b.j||f||d||((c=c&&c.ip)&&c.includes(":")&&(b.b|=4194304),a.sendRequest(b))}return h}
l.Ra=function(a){var b=a.url,c=new URL(b);if(c.search.startsWith("?d="))return a=this.a[a.tabId],this.ca("idmreg:"+b.substr(c.protocol.length),a&&a.url),{redirectUrl:chrome.extension.getURL("captured.html")}};
l.$=function(a){var b=a.tabId,c=a.frameId;if(!(0>b||0>c)){var d=a.requestId,e=a.url,f=M(e),h=a.type.endsWith("_frame");if(h){var g;g=[b,c].toString();var k=this.j;g=g in k?k[g]:k[g]=new ya(b,c,a.parentFrameId);g.a!=d&&(g.a=d,g.D=e,g.url=null,g.c=!1)}if(this.ka||f&128){e=this.B;g=this.S;k=!0;if(!g&&"POST"==a.method&&a.requestBody){var m=a.requestBody,n=m.raw;if(n)for(var p=0;p<n.length&&(n[p].bytes||(n=null));p++);n||m.formData?(d=this.g[d])?d.requestBody=m:G(this,a):k=!1}if(e&&k)switch(a.a=f,a.g=
a.requestBody,a.h=h,a.c=0<=y.indexOf(a.type),a.f=e,a.i=g,a.port=this.a[[b,c]],Ia(this,a)){case 5:if(v)return new Promise(this.Aa.bind(this,a));case 3:return X(this,a,null,!0)}}}};
l.aa=function(a){var b=a.tabId;if(0<b){var c=a.requestId,d=a.url,e=a.method,f=M(d);if(!f||"GET"!=e&&"POST"!=e)return X(this,a);a.f=this.B;a.i=this.S;if(c=this.g[c])a.id=c.id,a.port=c.port,a.g=c.requestBody,c.a&&(a.D=c.D||c.url,a.B=c.B||c.requestHeaders,a.m=c.m||c.g,a.f=c.f,a.i=c.i);var c=a.type,h=c.endsWith("_frame");if(!a.port&&!(a.port=this.a[[b,a.frameId]])&&!h||"POST"==e&&!a.g)return X(this,a);d.includes("#")&&(a.url=Na(d));a.a=f;a.h=h;a.c=0<=y.indexOf(c);a.u=la.test(d);switch(Ia(this,a)){case 5:if(v)return new Promise(this.Aa.bind(this,
a));if(!a.f)break;case 3:return X(this,a,null,!0);case 1:return X(this,a)}G(this,a)}return null};l.Aa=function(a,b,c){a.resolve=b;a.reject=c;G(this,a);this.sendRequest(a)};
l.ba=function(a){var b=this.g[a.requestId];if(b){var c=a.responseHeaders;if("image"==b.type){var d=Z(c,"Content-Type");if(d&&d.toLowerCase().startsWith("image/"))return X(this,b)}"quic"==Z(c,"Client-Protocol")?b.a|=64:(d=Z(c,"Alternate-Protocol"))&&d.endsWith(":quic,p=0")&&"chunked"!=Z(c,"Transfer-Encoding")&&(b.a|=64);if(this.ka||b.a&192){var d=a.statusLine,e=parseInt(d.split(" ",2).pop());b.statusLine=d;b.statusCode=e;b.H=0<=ha.indexOf(e);b.responseHeaders=c;if(3==Ka(this,b))return(a.ip||u)&&X(this,
b,a),r?{responseHeaders:[{name:"Connection",value:"close"},{name:"Content-Type",value:"multipart/related"},{name:"Content-Length",value:"0"}]}:{redirectUrl:chrome.extension.getURL("captured.html")}}}};l.Ta=function(a){var b=this.g[a.requestId];if(b){if(b.h){var c=this.j[[b.tabId,b.frameId]];c&&(c.url=b.url)}X(this,b,a)}};l.Sa=function(a){X(this,a.requestId)};
l.V=function(a,b,c,d,e){if(void 0===a&&(this.U=!1,a=new K(this,!0),chrome.storage.local.get("version",L(a,1)),r&&(chrome.extension.isAllowedIncognitoAccess(L(a,2)),chrome.management.get(da,L(a,3)),chrome.management.get(ea,L(a,4))),a.c()))return;a=chrome.runtime.getManifest();a=a.version||"";"object"==typeof b&&(b=b.version||"");r&&("object"==typeof d&&(d=d.enabled&&d.id),d&&chrome.management.setEnabled(d,!1),"object"==typeof e&&(e=e.enabled&&e.id),e&&chrome.management.setEnabled(e,!1),c=null!=c&&
!c);if(a&&a!=b&&null!=b){chrome.storage.local.set({version:a});d=this.T;var f=d<(u?ba:v?ca:0);if(!b||!d||f||e)a="current="+a,b&&(a+="&previous="+b),c&&(a+="&incognito=1"),e&&(a+="&mulsrch=1"),d&&(a+="&manager="+d),f&&(a+="&update=1"),u&&(a+="&msedge=1"),v&&(a+="&mzffox=1"),chrome.tabs.create({url:chrome.extension.getURL("welcome.html?"+a)})}};function V(a,b){var c=chrome.i18n.getMessage(b);v?chrome.tabs.executeScript(a,{code:'window.alert(unescape("'+escape(c)+'"))'}):window.alert(c)}
l.o=function(a,b){var c=Array.prototype.slice.call(arguments);if(v||u){var d=c[2];c[2]=function(){return d.apply(null,arguments)}}this.ma.push(c);b.addListener.apply(b,c.slice(2))};function K(a){this.caller=arguments.callee.caller;this.f=a;this.b=Array.prototype.slice.call(arguments,1);this.a=0}function L(a,b){a.a++;return a.h.bind(a,b)}K.prototype.c=function(){return this.a?(arguments.length&&(this.b=Array.prototype.slice.call(arguments)),!0):!1};
K.prototype.h=function(a,b){chrome.runtime.lastError;this.b[a]=b;0==--this.a&&this.caller.apply(this.f,this.b)};K.prototype.g=function(a,b,c){var d=Array.prototype.slice.call(arguments,3);c&&(d=c.concat(d));a.apply(b,d);this&&0==--this.a&&this.caller.apply(this.f,this.b)};function J(a){var b=Array.prototype.slice.call(arguments,1),c=b[b.length-1];c instanceof K?c.a++:c=null;return K.prototype.g.bind(c,arguments.callee.caller,a,b)}
function Na(a){var b=a.lastIndexOf("#");return 0>b||b<a.indexOf("?")?a:a.substr(0,b)}function N(a){var b="";if(a&&a.length)for(var c=0;c<a.length;c++)b&&(b+="; "),b+=a[c].name,b+="=",b+=a[c].value;return b}function Oa(a){if(!a||!a.length)return null;for(var b="",c=0;c<a.length;c++)b+=a[c].name,b+=": ",b+=a[c].value,b+="\n";return b}function Z(a,b){if(!a)return null;b=b.toLowerCase();for(var c=0;c<a.length;c++)if(a[c].name.toLowerCase()==b)return a[c].value;return null}
function Ma(a,b){if(!a)return null;b=b.toLowerCase();var c=a.split(";");c.shift();for(var d=0;d<c.length;d++){var e=c[d],f=e.indexOf("=");if(0<f){var h=e.substr(0,f).trim().toLowerCase(),g="*"==h[h.length-1];g&&(h=h.substr(0,h.length-1).trimRight());if(h==b)return c=e.substr(f+1).trim(),d=c.length-1,'"'==c[0]&&'"'==c[d]&&(c=c.substring(1,d)),g&&(c=c.split("'",3).pop()),unescape(c)}else if(0>f&&e.trim().toLowerCase()==b)return""}return null}
function La(a){return a&&unescape(a.split(";",1).shift().trim())||""}
function Pa(a,b){if(!a)return null;var c=a.raw;if(c){for(var d=String.fromCharCode,e="",f=0;f<c.length;f++){var h=c[f].bytes;if(!h)return null;for(var h=new Uint8Array(h),g=h.length,k=0;k<g;k++)e+=d(h[k])}return e}c=a.formData;if(!c)return null;f=La(b).toLowerCase();e=[];if("application/x-www-form-urlencoded"==f)for(d in c)for(h=c[d],d=d.split(" ").map(encodeURIComponent).join("+"),f=0;f<h.length;f++)e.length&&e.push("&"),e.push(d,"=",h[f].split(" ").map(encodeURIComponent).join("+"));else if("multipart/form-data"==
f){(g=Ma(b,"boundary"))||(g="----WebKitFormBoundary"+Math.random().toString(36).substr(2));for(d in c)for(h=c[d],f=0;f<h.length;f++)e.push("--",g,'\r\nContent-Disposition: form-data; name="',d,'"\r\n\r\n',h[f],"\r\n");e.push("--",g,"--\r\n")}else return null;return e.join("")}function Ja(a){return(a=ia.exec(a))?a.pop().toUpperCase():""}function M(a,b){var c=a.split("://",1).shift().toLowerCase(),c=va[c]||0;return b?c&31:c}
var Ca=[[-11,"menu_download_link","link,image",F.prototype.Ea],[-11,"menu_download_selected","selection",F.prototype.qa],[-12,"menu_download_all",v?"page,selection,link":"page",F.prototype.qa]];String.prototype.startsWith||(String.prototype.startsWith=function(a,b){return this.substr(b||0,a.length)===a});String.prototype.endsWith||(String.prototype.endsWith=function(a,b){b=(null==b||b>this.length?this.length:b)-a.length;return 0<=b&&this.lastIndexOf(a,b)==b});
String.prototype.includes||(String.prototype.includes=function(a,b){return 0<=this.indexOf(a,b)});new F;
